instance = "https://wom.handte.org:443/elastic/"
username = "wom"
password = ""
disable_security = true
index_name = "crawl-rawdata-ude"
batch_size = 100
pre_index = "preprocessing-ude"
research_project_index="research_project-ude"