instance = "https://wom.handte.org:443/elastic/"
username = "wom"
password = "H7kSk2~5GnybwE{}J4jdPj)qS74&tbXBK-b))+GN"
disable_security = true
index_name = "crawl-rawdata-ude"
batch_size = 100
pre_index = "preprocessing-ude"
research_project_index="research_project-ude"